// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxlsnqizmdjdsnqbksnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4bHNucWl6bWRqZHNucWJrc25tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwMDMyNjgsImV4cCI6MjA1MzU3OTI2OH0.3V-qjEDq-jSbfaDWxooJbg95dEj7aADoBeSdOyPrrt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);